
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALL AND CARDINALITY CLASS COLON COMMA DATA_TYPE DISJOINTCLASSES EQ EQUIVALENTTO EXACTLY GT HAS ID INDIVIDUALS IS LBRACE LBRACKET LPAREN LT MAX MIN NOT OF ONLY OR PROPERTY RBRACE RBRACKET RESERVED RPAREN SOME SUBCLASSOF THAT VALUE\n    ontologia : descricao_classes descricao_individuals\n    \n    descricao_classes : CLASS ID equivalencia_classes descricao_classes\n                      | CLASS ID subclasso_classes descricao_classes\n                      | CLASS ID disjoint_classes descricao_classes\n                      | \n    \n    equivalencia_classes : EQUIVALENTTO expressao_classes COMMA\n                         | EQUIVALENTTO expressao_classes\n    \n    subclasso_classes : SUBCLASSOF expressao_classes propriedades COMMA\n                      | SUBCLASSOF expressao_classes propriedades\n                      | SUBCLASSOF expressao_classes COMMA\n                      | SUBCLASSOF expressao_classes\n    \n    disjoint_classes : DISJOINTCLASSES LPAREN ID COMMA ID COMMA ID RPAREN COMMA\n                     | DISJOINTCLASSES LPAREN ID COMMA ID COMMA ID RPAREN\n    \n    propriedades : PROPERTY expressao_classes COMMA\n                 | PROPERTY expressao_classes\n    \n    expressao_classes : ID\n                      | ID AND LPAREN expressao_classes COMMA expressao_classes RPAREN\n                      | ID AND LPAREN expressao_classes COMMA ID SOME ID RPAREN\n                      | ID AND LPAREN ID SOME ID RPAREN\n                      | ID AND LPAREN ID COMMA ID SOME ID RPAREN\n    \n    descricao_individuals : CLASS ID COMMA ID descricao_individuals\n                          | CLASS ID COMMA descricao_individuals\n                          | \n    '
    
_lr_action_items = {'CLASS':([0,2,8,9,10,14,15,16,17,18,19,20,22,24,26,27,32,33,37,48,51,52,55,56,57,],[3,5,3,3,3,5,-2,-3,-4,-7,-16,-11,5,-6,-9,-10,-8,-15,-14,-19,-17,-13,-12,-20,-18,]),'$end':([0,1,2,4,8,9,10,14,15,16,17,18,19,20,22,23,24,26,27,30,32,33,37,48,51,52,55,56,57,],[-5,0,-23,-1,-5,-5,-5,-23,-2,-3,-4,-7,-16,-11,-23,-22,-6,-9,-10,-21,-8,-15,-14,-19,-17,-13,-12,-20,-18,]),'ID':([3,5,11,12,14,21,28,31,34,39,40,41,42,49,50,],[6,7,19,19,22,29,19,35,38,43,44,45,47,53,54,]),'EQUIVALENTTO':([6,],[11,]),'SUBCLASSOF':([6,],[12,]),'DISJOINTCLASSES':([6,],[13,]),'COMMA':([7,18,19,20,26,29,33,35,36,37,38,48,51,52,56,57,],[14,24,-16,27,32,34,37,40,41,-14,42,-19,-17,55,-20,-18,]),'LPAREN':([13,25,],[21,31,]),'PROPERTY':([19,20,48,51,56,57,],[-16,28,-19,-17,-20,-18,]),'AND':([19,35,45,],[25,25,25,]),'SOME':([35,44,45,],[39,49,50,]),'RPAREN':([43,45,46,47,48,51,53,54,56,57,],[48,-16,51,52,-19,-17,56,57,-20,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ontologia':([0,],[1,]),'descricao_classes':([0,8,9,10,],[2,15,16,17,]),'descricao_individuals':([2,14,22,],[4,23,30,]),'equivalencia_classes':([6,],[8,]),'subclasso_classes':([6,],[9,]),'disjoint_classes':([6,],[10,]),'expressao_classes':([11,12,28,31,41,],[18,20,33,36,46,]),'propriedades':([20,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ontologia","S'",1,None,None,None),
  ('ontologia -> descricao_classes descricao_individuals','ontologia',2,'p_ontologia','App.py',211),
  ('descricao_classes -> CLASS ID equivalencia_classes descricao_classes','descricao_classes',4,'p_descricao_classes','App.py',216),
  ('descricao_classes -> CLASS ID subclasso_classes descricao_classes','descricao_classes',4,'p_descricao_classes','App.py',217),
  ('descricao_classes -> CLASS ID disjoint_classes descricao_classes','descricao_classes',4,'p_descricao_classes','App.py',218),
  ('descricao_classes -> <empty>','descricao_classes',0,'p_descricao_classes','App.py',219),
  ('equivalencia_classes -> EQUIVALENTTO expressao_classes COMMA','equivalencia_classes',3,'p_equivalencia_classes','App.py',224),
  ('equivalencia_classes -> EQUIVALENTTO expressao_classes','equivalencia_classes',2,'p_equivalencia_classes','App.py',225),
  ('subclasso_classes -> SUBCLASSOF expressao_classes propriedades COMMA','subclasso_classes',4,'p_subclasso_classes','App.py',230),
  ('subclasso_classes -> SUBCLASSOF expressao_classes propriedades','subclasso_classes',3,'p_subclasso_classes','App.py',231),
  ('subclasso_classes -> SUBCLASSOF expressao_classes COMMA','subclasso_classes',3,'p_subclasso_classes','App.py',232),
  ('subclasso_classes -> SUBCLASSOF expressao_classes','subclasso_classes',2,'p_subclasso_classes','App.py',233),
  ('disjoint_classes -> DISJOINTCLASSES LPAREN ID COMMA ID COMMA ID RPAREN COMMA','disjoint_classes',9,'p_disjoint_classes','App.py',238),
  ('disjoint_classes -> DISJOINTCLASSES LPAREN ID COMMA ID COMMA ID RPAREN','disjoint_classes',8,'p_disjoint_classes','App.py',239),
  ('propriedades -> PROPERTY expressao_classes COMMA','propriedades',3,'p_propriedades','App.py',244),
  ('propriedades -> PROPERTY expressao_classes','propriedades',2,'p_propriedades','App.py',245),
  ('expressao_classes -> ID','expressao_classes',1,'p_expressao_classes','App.py',250),
  ('expressao_classes -> ID AND LPAREN expressao_classes COMMA expressao_classes RPAREN','expressao_classes',7,'p_expressao_classes','App.py',251),
  ('expressao_classes -> ID AND LPAREN expressao_classes COMMA ID SOME ID RPAREN','expressao_classes',9,'p_expressao_classes','App.py',252),
  ('expressao_classes -> ID AND LPAREN ID SOME ID RPAREN','expressao_classes',7,'p_expressao_classes','App.py',253),
  ('expressao_classes -> ID AND LPAREN ID COMMA ID SOME ID RPAREN','expressao_classes',9,'p_expressao_classes','App.py',254),
  ('descricao_individuals -> CLASS ID COMMA ID descricao_individuals','descricao_individuals',5,'p_descricao_individuals','App.py',259),
  ('descricao_individuals -> CLASS ID COMMA descricao_individuals','descricao_individuals',4,'p_descricao_individuals','App.py',260),
  ('descricao_individuals -> <empty>','descricao_individuals',0,'p_descricao_individuals','App.py',261),
]
